# Generated by Django 6.0.2 on 2026-05-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
